name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 21

      - name: Verify Gradle Wrapper Files
        run: |
          if [ ! -f gradle/wrapper/gradle-wrapper.jar ]; then
            echo "Gradle wrapper files are missing. Regenerating..."
            gradle wrapper --gradle-version 7.6
          fi

      - name: Run ktlint
        run: ./gradlew ktlintCheck

      - name: Run tests
        run: ./gradlew test
